### ISSUE TITLE
프로그램 제작에 감사드립니다.

### ISSUE THREAD

**Issue by 294nikusi** [009342/Nico-Nico-Video-Translator#1]
유용한 프로그램 제작에 감사드립니다.
알려주신 방법대로 설정을 하고 실행했더니 첨부한 사진과 같이
코멘트를 불러올 수 없다는 오류와 함께 모든 코멘트들이 전부 보이지 않고
프로그램 내에서는 이렇게만 뜨고있습니다.
윈도우10을 사용중이고 네이버 웨일 브라우저를 사용중입니다.
크롬 브라우저로도 사용을 해봤는데 똑같은 오류가 발생되었습니다.

![2](https://user-images.githubusercontent.com/40436515/44530924-82386880-a72a-11e8-8997-1ae190f552e2.PNG)
![3](https://user-images.githubusercontent.com/40436515/44530925-82386880-a72a-11e8-9dd6-8b053c409458.PNG)
![default](https://user-images.githubusercontent.com/40436515/44530926-82386880-a72a-11e8-99f6-52ab3f53a89e.PNG)

**Comment by 009342** [comment]
니코동에서 http연결을 https 보안연결로 대체하였습니다.
조금 많이 복잡해져서, 프로그램 구성을 갈아엎어야 할지도 모르겠네요.
제보 감사합니다!

**Comment by 009342** [comment]
node.js 버전 추가로 해결했습니다. 후에 README파일과 함께 사용법을 올리도록 하겠습니다.
