### ISSUE TITLE
오류 제보

### ISSUE THREAD

**Issue by jhdaniel99** [009342/Nico-Nico-Video-Translator#2]
//에러 전문
2
서버가 127.0.0.1:80에서 작동되고 있습니다...
접속 :127.0.0.1:7228
접속해제 :127.0.0.1:7228
접속 :127.0.0.1:7315
접속 :127.0.0.1:7337
Host: nmsg.nicovideo.jp
Origin: http://www.nicovideo.jp
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
DNT: 1
Content-Type: text/plain;charset=UTF-8
Accept: */*
Referer: http://www.nicovideo.jp/watch/sm6704029
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9,ko;q=0.8
클라이언트와의 연결에서 오류가 발생했습니다. 자세한 오류는 아래를 참고해주시기 바랍니다.
System.Net.WebException: 원격 서버에서 (500) 내부 서버 오류 오류를 반환했습니다.
   위치: System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
   위치: System.Net.WebClient.UploadString(Uri address, String method, String data)
   위치: PapagoTranslateAPI.PapagoTranslate.Translate(String source, String target, String text, String mode)
   위치: NicoNicoTranslator.NicoNicoServer.<RunServerThreadAsync>d__12.MoveNext()
접속해제 :127.0.0.1:7315

영상 링크: http://www.nicovideo.jp/watch/sm6704029
크롬 환경에서 일어난 오류입니다.

**Comment by 009342** [comment]
니코동에서 기존의 http연결을 https보안 연결로 대체했습니다.
조금 많이 복잡해져서, 프로그램 구성을 갈아엎어야 할 것 같습니다.
제보 감사합니다!

**Comment by 009342** [comment]
node.js 버전 추가로 해결했습니다. 후에 README파일과 함께 사용법을 올리도록 하겠습니다.

**Comment by jhdaniel99** [comment]
정말 수고하셨습니다! 감사드려요!
덕분에 일본어를 모르는 입장에서도 즐거운 니코동 감상이 되겠어요! 다시 한번 감사드립니다!


2018년 10월 25일 (목) 오후 7:50, 009342 <notifications@github.com>님이 작성:

**Comment by 009342** [comment]
사용법을 추가했습니다!
https://github.com/009342/Nico-Nico-Video-Translator/blob/master/README-nodejs.md
혹시라도 다른 문제가 생기면 블로그의 댓글란이나, 이 리포지토리의 이슈탭에 제보해주시면 정말 감사하겠습니다 :)
