### ISSUE TITLE
443포트가 사용중인 경우 오작동

### ISSUE THREAD

**Issue by AcidF0x** [009342/Nico-Nico-Video-Translator#5]
호스트가 443포트를 사용중인 경우  
별도로 에러가 발생하지 않고 실행이 되며  
기능이 동작하지 않습니다

**Comment by 009342** [comment]
생각나는 해결법이 존재하지가 않네요.
443포트는 HTTPS의 기본 포트이니 별도의 서버에서 구동시키거나 따로 처리를 해 주는 방법 외에는 별다는 방법은 없을 것 같습니다.

**Comment by AcidF0x** [comment]
@009342 일단 Close하겠습니다.
일반적인 환경에서는 이슈가 발생하지 않은데.
로컬에서 개발서버를 돌리고있어서 불편해서 이슈 남겨습니다.
해결법은 추후 연구해서 PR하겠습니다.
