### ISSUE TITLE
니코동 영상 들어가면 아예 코멘트가 없어지네요

### ISSUE THREAD

**Issue by Timeffect0** [009342/Nico-Nico-Video-Translator#6]
run.bat를 시작 해도
node은(는) 내부 또는 외부 명령, 실행 할 수 있는 프로그램, 또는
배치 파일이 아닙니다.

만 뜨네요

127.0.0.1 nmsg.nicovideo.jp 이걸 지우면 다시 코멘트가 뜨기는 하는데
번역은 안 돼네요
다시 넣으면 코멘트 자체가 사라져 버리고

**Comment by AcidF0x** [comment]
node를 설치하셨나요?
node가 설치가 되있더라도 Path에 등록이 안되어있을수도 있습니다.
명령프롬프트를 실행하시고 `node  -v`라고 입력해보시면 Path에 등록되있는지 확인 하실수있습니다.

Node를 설치하지 않은 경우 -> Node를 설치한다.
Node를 설치하였는데도 안되는 경우 -> Node Path를 확인한다.

**Comment by 009342** [comment]
nmsg.nicovideo.jp의 IP주소가 변경되어서 생긴 오류였습니다.
DNS에서 nmsg.nicovideo.jp의 주소를 가져오도록 수정하였으니, 새로운 Release를 확인해주세요!

https://github.com/009342/Nico-Nico-Video-Translator/releases/tag/1.1-nodejs
