### ISSUE TITLE
run 실행하고 영상 재생해도 번역이 안 되네요

### ISSUE THREAD

**Issue by user-3-22** [009342/Nico-Nico-Video-Translator#9]
audited 95 packages in 0.929s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities

NicoNicoTranslator (1.0-nodejs)
오류 제보 : https://github.com/009342/Nico-Nico-Video-Translator/issues
제작자 블로그 : http://sshbrain.tistory.com

HTTPS 서버가 작동 중입니다.
(node:9852) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request.<anonymous> (C:\Users\ehkcu\Downloads\Release\app.js:51:37)
    at Generator.next (<anonymous>)
    at C:\Users\ehkcu\Downloads\Release\app.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\ehkcu\Downloads\Release\app.js:3:12)
    at Request._callback (C:\Users\ehkcu\Downloads\Release\app.js:50:20)
    at self.callback (C:\Users\ehkcu\Downloads\Release\node_modules\request\request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.onRequestError (C:\Users\ehkcu\Downloads\Release\node_modules\request\request.js:877:8)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9852) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9852) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

run 실행하고 재생하면 코멘트가 안 뜨고  저렇게 오류가 뜨는데 뭐가 문제일까요..ㅠ

**Comment by 009342** [comment]
안녕하세요, 오류 제보 감사드립니다.
현재 해당 오류의 원인을 확인하였고, 네이버 파파고쪽 번역 API의 사양이 바뀐 탓에 오류가 발생하는 것으로 확인되었습니다.
현재 일정이 조금 밀려있어 오류를 수정하는 것이 조금 늦어질 것 같습니다.
잠시만 기다려주시면 감사하겠습니다!

**Comment by 009342** [comment]
해당 오류를 해결한 버전을 업데이트 하였습니다.  
https://github.com/009342/Nico-Nico-Video-Translator/releases 에서 해당 업데이트를 다운로드받으실 수 있습니다.
